name: catchemi 
channels:
  - conda-forge
  - defaults
dependencies:
  - arb
  - cython
  - matplotlib
  - monty
  - mpmath
  - numpy
  - pip
  - pymatgen
  - scipy
  - setuptools
  - sympy
  - tabulate